name: Android kernel builder

on:
  workflow_dispatch:

jobs:
  buildkernel:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Build kernel 
        continue-on-error: true
        env:
           TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: bash build.sh
        
